version: '3'
services:
  selenoid:
    image: "aerokube/selenoid:latest-release"
    network_mode: bridge
    container_name: selenoid
    ports:
    - "4444:4444"
    environment:
      OVERRIDE_VIDEO_OUTPUT_DIR: ${PWD}/../logs/video/
    volumes:
    - "./browsers:/etc/selenoid"
    - "../logs/video:/opt/selenoid/video/"
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "../logs/selenoid_logs/:/opt/selenoid/logs/"
    command: ["-log-output-dir","/opt/selenoid/logs"]
  selenoid-ui:
    image: "aerokube/selenoid-ui:latest-release"
    network_mode: bridge
    container_name: selenoid-ui
    links:
    - selenoid
    ports:
    - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
  db:
    image: mysql:8.0
    container_name: mysql-server-80
    command: --default-authentication-plugin=mysql_native_password --init-file /data/database/init.sql
    volumes:
    - "./init.sql:/data/database/init.sql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwe123QWE
      MYSQL_DATABASE: test_base
      MYSQL_USER: test_user
      MYSQL_PASSWORD: qwerty
    ports:
    - "3306:3306"
  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: "TRUE"
    ports:
    - "4040:4040"
    - "5050:5050"
    volumes:
    - ${PWD}/../logs:/app/allure-results