version: '3'
services:
  selenoid:
    image: "aerokube/selenoid:latest-release"
    network_mode: bridge
    container_name: selenoid
    ports:
    - "4444:4444"
    env_file: .env
    volumes:
    - "./browsers:/etc/selenoid"
    - "../logs/video:/opt/selenoid/video/"
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "../logs/selenoid_logs/:/opt/selenoid/logs/"
    command: ["-save-all-logs" ,"-log-output-dir","/opt/selenoid/logs"]
  selenoid-ui:
    image: "aerokube/selenoid-ui:latest-release"
    network_mode: bridge
    container_name: selenoid-ui
    links:
    - selenoid
    ports:
    - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]